### ISSUE TITLE
你好问下，这个支持在ts项目引入使用吗

### ISSUE THREAD

**Issue by WizardInfinite** [kokiy/react-h5-calendar#2]

**Comment by kokiy** [comment]
当然可以 ,这个只是一个lib ,ts 环境下js 环境下都可以的

**Comment by WizardInfinite** [comment]
好的，谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "子宓"<notifications@github.com&gt;; 
发送时间: 2021年1月15日(星期五) 下午5:57
收件人: "kokiy/react-h5-calendar"<react-h5-calendar@noreply.github.com&gt;; 
抄送: "天亮未晚"<1678057769@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [kokiy/react-h5-calendar] 你好问下，这个支持在ts项目引入使用吗 (#2)





 
当然可以 ,这个只是一个lib ,ts 环境下js 环境下都可以的

**Comment by WizardInfinite** [comment]
你好，我引入了之后，样式没有生效，请问什么原因呢

**Comment by kokiy** [comment]
> 你好，我引入了之后，样式没有生效，请问什么原因呢
light-react-calendar 试一下这个包  这个 h5-calendar 没有把less编译成css
